-- Phase 10: agent-to-agent messaging. Kratos is the single source of truth and
-- broker. Messages live in the DB; delivery notifications go to the receiver's
-- tmux when it is idle (see lib/agent-talk.js).
CREATE TABLE agent_messages (
  id          TEXT PRIMARY KEY,            -- message-id (uuid, generated by Kratos)
  sender_id   INTEGER NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
  receiver_id INTEGER NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
  body        TEXT NOT NULL,
  created_at  TEXT NOT NULL DEFAULT (datetime('now')),
  read_at     TEXT DEFAULT NULL,           -- NULL = unread
  notified_at TEXT DEFAULT NULL            -- NULL = tmux notification not yet sent
);

CREATE INDEX idx_msg_pair  ON agent_messages(sender_id, receiver_id);
CREATE INDEX idx_msg_inbox ON agent_messages(receiver_id, read_at);

-- Opt-in: only agents that asked receive idle-time message notifications.
ALTER TABLE agents ADD COLUMN wants_message_notify INTEGER NOT NULL DEFAULT 0;
