import fs from 'fs';
import path from 'path';

const PRIORITY_LABELS = { 1: 'P1', 2: 'P2', 3: 'P3', 4: 'P4', 5: 'P5' };

function getAuthorName(db, type, id) {
  if (type === 'user') {
    return db.prepare('SELECT username FROM users WHERE id = ?').get(id)?.username || 'unknown';
  }
  return db.prepare('SELECT name FROM agents WHERE id = ?').get(id)?.name || 'unknown';
}

export function exportIssue(db, issue) {
  const project = db.prepare('SELECT * FROM projects WHERE code = ?').get(issue.project_code);
  if (!project) return;

  const historyDir = path.join(project.folder, 'history');
  fs.mkdirSync(historyDir, { recursive: true });

  const issueId = `${issue.project_code}-${issue.issue_number}`;
  const reporter = getAuthorName(db, issue.reporter_type, issue.reporter_id);
  const assignee = issue.assignee_agent_id
    ? db.prepare('SELECT name FROM agents WHERE id = ?').get(issue.assignee_agent_id)?.name || '-'
    : '-';

  // Build issue file
  const comments = db.prepare(
    'SELECT * FROM comments WHERE issue_id = ? ORDER BY created_at'
  ).all(issue.id);

  let md = `<!-- This file is auto-generated by Kratos. READ-ONLY — do not edit directly. -->\n`;
  md += `<!-- Use Kratos UI or API to modify issues. Changes to this file will be overwritten. -->\n\n`;
  md += `# ${issueId}: ${issue.title}\n\n`;
  md += `- **Status**: ${issue.status}\n`;
  md += `- **Priority**: ${PRIORITY_LABELS[issue.priority]}\n`;
  md += `- **Reporter**: ${reporter}\n`;
  md += `- **Assignee**: ${assignee}\n`;
  md += `- **Created**: ${issue.created_at?.slice(0, 10)}\n`;
  md += `- **Updated**: ${issue.updated_at?.slice(0, 10)}\n\n`;
  md += `## Description\n\n${issue.description || '(no description)'}\n`;

  if (comments.length > 0) {
    md += `\n## Comments\n`;

    const topLevel = comments.filter(c => !c.parent_id);
    const replies = comments.filter(c => c.parent_id);
    const replyMap = {};
    for (const r of replies) {
      if (!replyMap[r.parent_id]) replyMap[r.parent_id] = [];
      replyMap[r.parent_id].push(r);
    }

    for (const c of topLevel) {
      const author = getAuthorName(db, c.author_type, c.author_id);
      md += `\n### ${author} (${c.created_at?.slice(0, 16).replace('T', ' ')})\n\n${c.body}\n`;

      const childReplies = replyMap[c.id] || [];
      for (const r of childReplies) {
        const rAuthor = getAuthorName(db, r.author_type, r.author_id);
        md += `\n#### ${rAuthor} (${r.created_at?.slice(0, 16).replace('T', ' ')})\n\n${r.body}\n`;
      }
    }
  }

  fs.writeFileSync(path.join(historyDir, `${issueId}.md`), md);

  // Update README.md
  exportReadme(db, project);
}

export function exportReadme(db, project) {
  const historyDir = path.join(project.folder, 'history');
  fs.mkdirSync(historyDir, { recursive: true });

  const issues = db.prepare(
    'SELECT * FROM issues WHERE project_code = ? ORDER BY issue_number'
  ).all(project.code);

  let md = `<!-- This file is auto-generated by Kratos. READ-ONLY — do not edit directly. -->\n\n`;
  md += `# ${project.code} Issues\n\n`;

  if (issues.length === 0) {
    md += 'No issues yet.\n';
  } else {
    md += `| # | Status | Priority | Title | Reporter | Assignee |\n`;
    md += `|---|--------|----------|-------|----------|----------|\n`;

    for (const issue of issues) {
      const issueId = `${issue.project_code}-${issue.issue_number}`;
      const reporter = getAuthorName(db, issue.reporter_type, issue.reporter_id);
      const assignee = issue.assignee_agent_id
        ? db.prepare('SELECT name FROM agents WHERE id = ?').get(issue.assignee_agent_id)?.name || '-'
        : '-';
      md += `| [${issueId}](${issueId}.md) | ${issue.status} | ${PRIORITY_LABELS[issue.priority]} | ${issue.title} | ${reporter} | ${assignee} |\n`;
    }
  }

  fs.writeFileSync(path.join(historyDir, 'README.md'), md);
}
